# Generated by Django 5.2.4 on 2025-07-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('acoustic', 'Acoustic')], default='residential', max_length=20),
        ),
    ]
