# Generated by Django 5.2.4 on 2025-07-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
