# Generated by Django 5.2.4 on 2025-07-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('tile', 'Tile'), ('gypsum', 'Gypsum'), ('pvc', 'PVC'), ('partition', 'Partition'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
