# Generated by Django 5.2.4 on 2025-07-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_myservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='myservices/')),
                ('category', models.CharField(choices=[('tile', 'Tile'), ('gypsum', 'Gypsum'), ('partition', 'Partition'), ('pvc', 'PVC'), ('repairing', 'Repairing'), ('others', 'Others')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('material_used', models.CharField(max_length=100)),
                ('completed_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='MyService',
        ),
    ]
