# Generated by Django 5.2.4 on 2025-07-27 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_myservices_delete_myservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myservices',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='myservices',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='myservices',
            name='location',
        ),
        migrations.RemoveField(
            model_name='myservices',
            name='material_used',
        ),
        migrations.AddField(
            model_name='myservices',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='myservices',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myservices',
            name='price_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
