# Generated by Django 5.2.4 on 2025-07-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_myservices_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myservices',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
