# Generated by Django 5.2.4 on 2025-07-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_myservices_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
