# Generated by Django 5.2.4 on 2025-07-27 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tile', 'Tile'), ('gypsum', 'Gypsum'), ('pvc', 'PVC'), ('partition', 'Partition'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
