# Generated by Django 5.2.4 on 2025-09-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_locationprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstimateRequest',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
