# Generated by Django 5.2.4 on 2025-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_estimaterequest_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationprice',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='locationprice',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
