# Generated by Django 5.2.4 on 2025-09-29 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_locationprice_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactServiceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.myservices')),
            ],
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=250)),
                ('design', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('services', models.ManyToManyField(through='app.ContactServiceSelection', to='app.myservices')),
            ],
        ),
        migrations.AddField(
            model_name='contactserviceselection',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contactsubmission'),
        ),
    ]
