# Generated by Django 5.2.4 on 2025-09-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_contactserviceselection_contactsubmission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
