# Generated by Django 5.2.4 on 2025-09-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='design',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
